### PR TITLE
Task 7 done and working

### PR DESCRIPTION
**Pull request by hamzahdili2001**
there is still a problem I don't understand in the `do_update` method when I do `string.to_dict()` or `string.save()` there is an error "cannot access member `save` for type `str`" and the same for `to_dict` If you can find the issue tell me. Well the only method that does not work correct is `to_update`, all the functions work fine.

### CODE REVIEW

**Comment by MrSakine** [comment]
> there is still a problem I don't understand in the `do_update` method when I do `string.to_dict()` or `string.save()` there is an error "cannot access member `save` for type `str`" and the same for `to_dict` If you can find the issue tell me. Well the only method that does not work correct is `to_update`, all the functions work fine.

alright, what about test suites ?

**Comment by MrSakine** [comment]
delete isn't working either

**Comment by MrSakine** [comment]
I think it related to task 5, give me some times to fix it

**Review by MrSakine — APPROVED** [review]

**Comment by MrSakine** [comment]
I'm unable to get all the attributes, it only gets named ones, not unnamed

**Comment by MrSakine** [comment]
> I'm unable to get all the attributes, it only gets named ones, not unnamed

Fixed

**Review by MrSakine — APPROVED** [review]

**Review by hamzahdili2001 — COMMENTED** [review]
Good Job, You Merge Now

**Comment by MrSakine** [comment]
> Good Job, You Merge Now

thanks you

**Pull request merged**
